# <center> <b> <h1> Borda Most Significant Rois</h1></b></center>

In [13]:
import pandas as pd
import numpy as np 

PATH_SIGNIFICANCE = "../1. SVM RFE (All features)/output/"
PATH_USED = "../1. SVM RFE (All features)/csv/"

In [14]:
def readSignificances():
    
    datasets = []
    constant1 = 'best_regions_normalized_'
    features = ['area','meancurv', 'thickness', 'volume']
    # features for paper
    features = ['area', 'volume']

    for feature in features:
        df = pd.read_csv(PATH_SIGNIFICANCE + constant1 + feature +'.csv', index_col=0)
        df.sort_values('frecuency', inplace = True, ascending=False)
        datasets.append({'name': feature, 'data': df})
    return datasets

In [15]:
# Names are ordered whit significance, mos significant first
def clean_featuere_of_name_cols(df, name_feature):
    array_names = []
    name_feature_temp = '_' + name_feature
    for name in df.index.values:
        name = name.replace(name_feature_temp, '')
        array_names.append(name)

    return array_names

# 1. Prepare the data

In [16]:
Significances = readSignificances()
Significances[1]['data'].head()

                                 frecuency  variation (a/k)
Name
lh_S_orbital_med-olfact_volume         454        40.441839
lh_G_temp_sup-Plan_polar_volume        437        36.088412
lh_Pole_occipital_volume               375        31.210326
lh_G_orbital_volume                    326        21.901694
rh_G_front_sup_volume                  298        17.853473

In [17]:
ordered_vectors = []

for significance in Significances:
    data = significance['data']
    name = significance['name']
    #print(name)
    ordered_vectors.append(clean_featuere_of_name_cols(data, name))

print(len(ordered_vectors[0]))

148

# Create a df for the results

In [18]:
df_results = pd.DataFrame(columns=['Name', 'votes', 'area', 'vol'])
df_results['Name'] = ordered_vectors[0]
df_results['votes'] = 0
df_results['area'] = 0
df_results['vol'] = 0
df_results.set_index('Name', inplace = True)
df_results.shape

(148, 3)

In [19]:
"""for vector in ordered_vectors:
    position = 0
    for region in vector:
        coordinate = df_results.at[region, 'votes']
        result = coordinate + position
        df_results.at[region, 'votes'] = result
        position += 1"""

"for vector in ordered_vectors:\n    position = 0\n    for region in vector:\n        coordinate = df_results.at[region, 'votes']\n        result = coordinate + position\n        df_results.at[region, 'votes'] = result\n        position += 1"

In [20]:
#this is just for correct paper
area = True
#this is just for correct paper

for vector in ordered_vectors:
    position = 0
    for region in vector:
        if area:
            pos = 11
        else:
            pos = 14
        if position <= pos:
            coordinate = df_results.at[region, 'votes']
            result = coordinate + position
            df_results.at[region, 'votes'] = result
            if area:
                df_results.at[region, 'area'] = position
            else:
                df_results.at[region, 'vol'] = position
        else:
            coordinate = df_results.at[region, 'votes']
            result = 500
            df_results.at[region, 'votes'] = result
            
        position += 1
    area = False

In [21]:
df_results.head()

                         votes  area  vol
Name
lh_G_and_S_frontomargin      5     0    5
lh_Pole_occipital            3     1    2
rh_S_oc-temp_lat             9     2    7
lh_S_orbital_med-olfact      3     3    0
rh_G_occipital_sup         500     4    0

In [22]:
df_results.sort_values('votes', inplace = True)

In [26]:
df_results.head(25)

                             votes  area  vol
Name
lh_Pole_occipital                3     1    2
lh_S_orbital_med-olfact          3     3    0
lh_G_and_S_frontomargin          5     0    5
rh_S_oc-temp_lat                 9     2    7
rh_S_collat_transv_post         23    11   12
rh_S_interm_prim-Jensen        500     0    0
rh_G_and_S_subcentral          500     0    0
lh_G_Ins_lg_and_S_cent_ins     500     0    0
lh_S_collat_transv_post        500     0    0
lh_G_temp_sup-Plan_tempo       500     0    0
rh_G_and_S_frontomargin        500     0    0
lh_S_oc_sup_and_transversal    500     0    0
rh_S_calcarine                 500     0    0
lh_S_front_inf                 500     0    0
rh_G_precentral                500     0    0
lh_G_cingul-Post-dorsal        500     0    0
lh_S_occipital_ant             500     0    0
rh_G_pariet_inf-Supramar       500     0    0
rh_G_and_S_paracentral         500     0    0
lh_G_and_S_cingul-Mid-Post     500     0    0
rh_S_circular_insula_inf       500     0    0
lh_G_pariet_inf-Supramar       500     0    0
rh_S_circular_insula_sup       500     0    0
lh_Pole_temporal               500     0    0
rh_G_front_inf-Orbital         500     0    0

In [27]:
df_results.to_csv("output/borda classification SVM Normalized.csv")